<?php
// Inventory Report PDF template
$document_type = 'Inventory Report';
$document_number = 'RPT-' . date('Ymd-His');
$document_date = date('M d, Y');
$status = 'Generated';

// Company information
$company_name = 'MISP System';
$company_tagline = 'Management Information System for Spare Parts';
$company_address = "123 Business Street\nCity, State 12345\nCountry";
$company_phone = '+1 (555) 123-4567';
$company_email = 'info@mispsystem.com';
$company_website = 'www.mispsystem.com';

// Footer information
$footer_disclaimer = "This report is generated automatically by MISP System.\nData is current as of " . date('M d, Y H:i T') . ".\nConfidential - For authorized personnel only.";
$contact_info = "Questions? Contact us at support@mispsystem.com";

ob_start();
?>

<!-- Report Summary -->
<div class="content-section">
    <div class="summary-section">
        <h3 class="section-title">Report Summary</h3>
        <div style="display: flex; justify-content: space-between; gap: 20px;">
            <div style="flex: 1;">
                <div class="info-box">
                    <h4>Report Parameters</h4>
                    <p><strong>Report Type:</strong> <?= htmlspecialchars($report_type ?? 'Full Inventory') ?></p>
                    <p><strong>Date Range:</strong> <?= htmlspecialchars($date_range ?? 'All Time') ?></p>
                    <p><strong>Warehouses:</strong> <?= htmlspecialchars($warehouses ?? 'All Locations') ?></p>
                    <p><strong>Categories:</strong> <?= htmlspecialchars($categories ?? 'All Categories') ?></p>
                    <p><strong>Generated By:</strong> <?= htmlspecialchars($generated_by ?? 'System') ?></p>
                </div>
            </div>
            
            <div style="flex: 1;">
                <div class="info-box">
                    <h4>Inventory Overview</h4>
                    <p><strong>Total Products:</strong> <?= number_format($total_products ?? 0) ?></p>
                    <p><strong>Total Value:</strong> <?= number_format($total_value ?? 0, 2) ?> <?= $currency ?? 'USD' ?></p>
                    <p><strong>Low Stock Items:</strong> <?= number_format($low_stock_items ?? 0) ?></p>
                    <p><strong>Out of Stock:</strong> <?= number_format($out_of_stock_items ?? 0) ?></p>
                    <p><strong>Active Warehouses:</strong> <?= number_format($active_warehouses ?? 0) ?></p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Stock Status Overview -->
<?php if (!empty($stock_status_summary)): ?>
<div class="content-section">
    <h3 class="section-title">Stock Status Overview</h3>
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 25%;">Status</th>
                <th style="width: 15%; text-align: center;">Count</th>
                <th style="width: 15%; text-align: right;">Percentage</th>
                <th style="width: 20%; text-align: right;">Total Value</th>
                <th style="width: 25%;">Action Required</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($stock_status_summary as $status): ?>
            <tr>
                <td>
                    <span class="status-badge <?= strtolower($status['status']) ?>">
                        <?= htmlspecialchars($status['status']) ?>
                    </span>
                </td>
                <td class="text-center number"><?= number_format($status['count']) ?></td>
                <td class="text-right number"><?= number_format($status['percentage'], 1) ?>%</td>
                <td class="text-right number currency">
                    <?= number_format($status['value'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td style="font-size: 10px;">
                    <?= htmlspecialchars($status['action_required'] ?? 'None') ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<!-- Low Stock Alert Items -->
<?php if (!empty($low_stock_items) && is_array($low_stock_items)): ?>
<div class="content-section">
    <div class="info-box warning">
        <h4>⚠️ Low Stock Alert</h4>
        <p>The following items require immediate attention due to low stock levels:</p>
    </div>
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 25%;">Product</th>
                <th style="width: 15%;">SKU</th>
                <th style="width: 15%; text-align: center;">Current Stock</th>
                <th style="width: 15%; text-align: center;">Min. Level</th>
                <th style="width: 15%; text-align: right;">Unit Value</th>
                <th style="width: 15%;">Supplier</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($low_stock_items as $item): ?>
            <tr style="background-color: <?= ($item['current_stock'] <= 0) ? '#fff5f5' : '#fffef0' ?>;">
                <td>
                    <strong><?= htmlspecialchars($item['name']) ?></strong>
                    <?php if (!empty($item['category'])): ?>
                        <br><small style="color: #666;"><?= htmlspecialchars($item['category']) ?></small>
                    <?php endif; ?>
                </td>
                <td style="font-family: monospace; font-size: 10px;">
                    <?= htmlspecialchars($item['sku']) ?>
                </td>
                <td class="text-center number" style="color: <?= ($item['current_stock'] <= 0) ? '#dc3545' : '#ffc107' ?>; font-weight: bold;">
                    <?= number_format($item['current_stock']) ?>
                </td>
                <td class="text-center number">
                    <?= number_format($item['minimum_level']) ?>
                </td>
                <td class="text-right number">
                    <?= number_format($item['unit_price'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td style="font-size: 10px;">
                    <?= htmlspecialchars($item['supplier_name'] ?? 'TBD') ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<!-- Warehouse Breakdown -->
<?php if (!empty($warehouse_breakdown)): ?>
<div class="content-section">
    <h3 class="section-title">Warehouse Breakdown</h3>
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 25%;">Warehouse</th>
                <th style="width: 20%;">Location</th>
                <th style="width: 15%; text-align: center;">Total Items</th>
                <th style="width: 15%; text-align: right;">Total Value</th>
                <th style="width: 12%; text-align: center;">Low Stock</th>
                <th style="width: 13%; text-align: center;">Utilization</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($warehouse_breakdown as $warehouse): ?>
            <tr>
                <td>
                    <strong><?= htmlspecialchars($warehouse['name']) ?></strong>
                    <?php if (!empty($warehouse['manager'])): ?>
                        <br><small style="color: #666;">Manager: <?= htmlspecialchars($warehouse['manager']) ?></small>
                    <?php endif; ?>
                </td>
                <td style="font-size: 11px;">
                    <?= htmlspecialchars($warehouse['location']) ?>
                </td>
                <td class="text-center number">
                    <?= number_format($warehouse['total_items']) ?>
                </td>
                <td class="text-right number currency">
                    <?= number_format($warehouse['total_value'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td class="text-center">
                    <?php if ($warehouse['low_stock_count'] > 0): ?>
                        <span style="color: #dc3545; font-weight: bold;">
                            <?= number_format($warehouse['low_stock_count']) ?>
                        </span>
                    <?php else: ?>
                        <span style="color: #198754;">0</span>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <div style="background: #e9ecef; border-radius: 10px; height: 20px; position: relative;">
                        <div style="background: <?= ($warehouse['utilization'] > 80) ? '#dc3545' : (($warehouse['utilization'] > 60) ? '#ffc107' : '#198754') ?>; width: <?= $warehouse['utilization'] ?>%; height: 100%; border-radius: 10px;"></div>
                        <span style="position: absolute; top: 2px; left: 0; right: 0; text-align: center; font-size: 10px; font-weight: bold;">
                            <?= number_format($warehouse['utilization']) ?>%
                        </span>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<!-- Category Analysis -->
<?php if (!empty($category_analysis)): ?>
<div class="content-section">
    <h3 class="section-title">Category Analysis</h3>
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 30%;">Category</th>
                <th style="width: 15%; text-align: center;">Product Count</th>
                <th style="width: 20%; text-align: right;">Total Value</th>
                <th style="width: 15%; text-align: right;">Avg. Unit Price</th>
                <th style="width: 10%; text-align: center;">Turnover</th>
                <th style="width: 10%; text-align: center;">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($category_analysis as $category): ?>
            <tr>
                <td>
                    <strong><?= htmlspecialchars($category['name']) ?></strong>
                    <?php if (!empty($category['description'])): ?>
                        <br><small style="color: #666;"><?= htmlspecialchars($category['description']) ?></small>
                    <?php endif; ?>
                </td>
                <td class="text-center number"><?= number_format($category['product_count']) ?></td>
                <td class="text-right number currency">
                    <?= number_format($category['total_value'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td class="text-right number">
                    <?= number_format($category['avg_unit_price'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td class="text-center">
                    <?php 
                    $turnover_color = '#198754'; // Default green
                    if ($category['turnover_rate'] < 2) $turnover_color = '#dc3545'; // Red for low
                    elseif ($category['turnover_rate'] < 4) $turnover_color = '#ffc107'; // Yellow for medium
                    ?>
                    <span style="color: <?= $turnover_color ?>; font-weight: bold;">
                        <?= number_format($category['turnover_rate'], 1) ?>x
                    </span>
                </td>
                <td class="text-center">
                    <span class="status-badge <?= ($category['issues'] > 0) ? 'warning' : 'success' ?>">
                        <?= ($category['issues'] > 0) ? 'Issues' : 'OK' ?>
                    </span>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<!-- Top Value Items -->
<?php if (!empty($top_value_items)): ?>
<div class="content-section">
    <h3 class="section-title">Top Value Items</h3>
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 5%; text-align: center;">Rank</th>
                <th style="width: 30%;">Product</th>
                <th style="width: 15%;">SKU</th>
                <th style="width: 12%; text-align: center;">Stock</th>
                <th style="width: 13%; text-align: right;">Unit Price</th>
                <th style="width: 15%; text-align: right;">Total Value</th>
                <th style="width: 10%; text-align: center;">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($top_value_items as $index => $item): ?>
            <tr style="<?= ($index < 3) ? 'background-color: #f0f9f0;' : '' ?>">
                <td class="text-center">
                    <strong style="color: <?= ($index < 3) ? '#198754' : '#666' ?>;">
                        <?= $index + 1 ?>
                    </strong>
                </td>
                <td>
                    <strong><?= htmlspecialchars($item['name']) ?></strong>
                    <?php if (!empty($item['category'])): ?>
                        <br><small style="color: #666;"><?= htmlspecialchars($item['category']) ?></small>
                    <?php endif; ?>
                </td>
                <td style="font-family: monospace; font-size: 10px;">
                    <?= htmlspecialchars($item['sku']) ?>
                </td>
                <td class="text-center number">
                    <?= number_format($item['stock_quantity']) ?>
                </td>
                <td class="text-right number">
                    <?= number_format($item['unit_price'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td class="text-right number currency">
                    <strong><?= number_format($item['total_value'], 2) ?> <?= $currency ?? 'USD' ?></strong>
                </td>
                <td class="text-center">
                    <span class="status-badge <?= $item['stock_status'] ?>">
                        <?= ucfirst($item['stock_status']) ?>
                    </span>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<!-- Movement Analysis -->
<?php if (!empty($movement_analysis)): ?>
<div class="content-section">
    <h3 class="section-title">Recent Movement Analysis (Last 30 Days)</h3>
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 25%;">Product</th>
                <th style="width: 15%; text-align: center;">Inbound</th>
                <th style="width: 15%; text-align: center;">Outbound</th>
                <th style="width: 15%; text-align: center;">Net Change</th>
                <th style="width: 15%; text-align: right;">Movement Value</th>
                <th style="width: 15%;">Trend</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($movement_analysis as $movement): ?>
            <tr>
                <td>
                    <strong><?= htmlspecialchars($movement['product_name']) ?></strong>
                    <br><small style="color: #666;"><?= htmlspecialchars($movement['sku']) ?></small>
                </td>
                <td class="text-center number" style="color: #198754;">
                    +<?= number_format($movement['inbound_quantity']) ?>
                </td>
                <td class="text-center number" style="color: #dc3545;">
                    -<?= number_format($movement['outbound_quantity']) ?>
                </td>
                <td class="text-center number" style="color: <?= ($movement['net_change'] >= 0) ? '#198754' : '#dc3545' ?>;">
                    <?= ($movement['net_change'] >= 0) ? '+' : '' ?><?= number_format($movement['net_change']) ?>
                </td>
                <td class="text-right number">
                    <?= number_format($movement['movement_value'], 2) ?> <?= $currency ?? 'USD' ?>
                </td>
                <td class="text-center">
                    <?php 
                    $trend_icon = '→';
                    $trend_color = '#6c757d';
                    if ($movement['trend'] == 'increasing') {
                        $trend_icon = '↗';
                        $trend_color = '#198754';
                    } elseif ($movement['trend'] == 'decreasing') {
                        $trend_icon = '↘';
                        $trend_color = '#dc3545';
                    }
                    ?>
                    <span style="color: <?= $trend_color ?>; font-size: 16px; font-weight: bold;">
                        <?= $trend_icon ?>
                    </span>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<!-- Recommendations -->
<div class="content-section">
    <h3 class="section-title">Recommendations & Action Items</h3>
    
    <div style="display: flex; gap: 20px;">
        <div style="flex: 1;">
            <div class="info-box warning">
                <h4>⚠️ Immediate Actions Required</h4>
                <ul style="margin: 10px 0; padding-left: 20px; font-size: 11px;">
                    <?php if (($out_of_stock_items ?? 0) > 0): ?>
                    <li>Restock <?= $out_of_stock_items ?> out-of-stock items immediately</li>
                    <?php endif; ?>
                    <?php if (($low_stock_items_count ?? 0) > 0): ?>
                    <li>Review <?= $low_stock_items_count ?> items with low stock levels</li>
                    <?php endif; ?>
                    <li>Update minimum stock levels for frequently moving items</li>
                    <li>Contact suppliers for items with long lead times</li>
                </ul>
            </div>
        </div>
        
        <div style="flex: 1;">
            <div class="info-box">
                <h4>📊 Optimization Opportunities</h4>
                <ul style="margin: 10px 0; padding-left: 20px; font-size: 11px;">
                    <li>Review slow-moving inventory for potential disposal</li>
                    <li>Implement cycle counting for high-value items</li>
                    <li>Consider vendor-managed inventory for top suppliers</li>
                    <li>Optimize warehouse layout based on movement patterns</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Data Quality Notes -->
<div class="content-section">
    <div style="font-size: 10px; color: #666666; line-height: 1.4;">
        <h4>Report Notes:</h4>
        <ul style="margin: 5px 0; padding-left: 20px;">
            <li>Stock values are calculated using current unit prices</li>
            <li>Movement analysis covers the last 30 days of transaction history</li>
            <li>Low stock alerts are based on configured minimum levels</li>
            <li>Utilization percentages are calculated based on warehouse capacity</li>
            <li>This report excludes inactive and discontinued products</li>
        </ul>
        
        <p style="margin-top: 15px;">
            <strong>Report Generated:</strong> <?= date('M d, Y H:i:s T') ?> | 
            <strong>Next Scheduled Report:</strong> <?= date('M d, Y', strtotime('+1 week')) ?>
        </p>
    </div>
</div>

<?php
$content = ob_get_clean();
include 'layout.php';
?>